### PR TITLE
Improve Talented support

### LINKED ISSUE #3: Potential race condition when attaching to Talented
There is the potential for a race condition when attaching to Talented (if Talented loads before Talent Sequence 2). Current method also using extremely wide hook when any frame is created.

### PR DESCRIPTION
**Pull request by Road-block**
refactor detection of Talented addon to ensure it works regardless of addon loading order
avoid a very wide scope CreateFrame hook, hook only the relevant Talented method
change the backdrop when using Talented to match Talented

### CODE REVIEW

**Comment by mikeacjones** [comment]
@Road-block not sure if I'm missing something here, but when I apply these changes the Talent Sequence 2 addon no longer displays anything for me, regardless of whether I have Talented enabled or not.

**Comment by Road-block** [comment]
Clipboard 1
That's really strange. 
I have the opposite experience.

I did not get the addon loading at all with the original implementation and I think I know the reason.
Addon loading order while it is generally alphabetic, it is not deterministically so and especially on different OSes (win, mac, nix)

Hooking the CreateFrame function (which btw is a very far reaching hook) would only work if Talented's CreateFrame hasn't already run before the hook is installed by TalentSequence2.

So it relies on TalentSequence2 having loaded and ran its code before Talented addon loads, which as said is not guaranteed to happen for all clients.

Let's make sure we are both testing with the same Talented Classic addon [link](https://www.curseforge.com/wow/addons/talented-classic/files/3545183) and if that's the case, I'll make some additional changes for you to test.

**Comment by mikeacjones** [comment]
That all makes sense, and I had already seen a race condition before. I had assumed thought that Talented was actually loading its frame on demand - I had added in a print statement, which you don't see populated until you actually open the Talent UI for the first time. As such I had assumed that I would always get my hook installed before it was opened. And yeah.. I was not happy about the permissive hook, but I hadn't found another way to detect when the Frame was actually available to start manipulating. I tried `LoadWith` but was never able to get that to work for me.

I am on an M1 MacBook, as far as OS is concerned.

**Comment by Road-block** [comment]
Before I make more commits can you do me a favor?

After loading into the game run these few scripts and tell me what they report 😊 

1. `/dump GetAddOnInfo("Talented")`
2. `/dump GetAddOnEnableState((GetUnitName("player")),"Talented")`
3. `/dump LibStub("AceAddon-3.0"):GetAddon("Talented",true)`

If any of those return nil/error I'll have a better idea where the problem is.

**Comment by mikeacjones** [comment]
With current code in my branch I get this:

screenshot

And then after adding the code changes:

screenshot

**Comment by mikeacjones** [comment]
> * `/dump GetAddOnInfo("Talented")`

yes - give me a second

**Comment by mikeacjones** [comment]
> Before I make more commits can you do me a favor?
> 
> After loading into the game run these few scripts and tell me what they report 😊
> 
> 1. `/dump GetAddOnInfo("Talented")`
> 2. `/dump GetAddOnEnableState((GetUnitName("player")),"Talented")`
> 3. `/dump LibStub("AceAddon-3.0"):GetAddon("Talented",true)`
> 
> If any of those return nil/error I'll have a better idea where the problem is.

`/dump` isn't recognized as a valid command

**Comment by mikeacjones** [comment]
> 



> Before I make more commits can you do me a favor?
> 
> After loading into the game run these few scripts and tell me what they report 😊
Screen Shot 2022-01-21 at 1 44 43 AM
Screen Shot 2022-01-21 at 1 44 27 AM

> 
> 1. `/dump GetAddOnInfo("Talented")`
> 2. `/dump GetAddOnEnableState((GetUnitName("player")),"Talented")`
> 3. `/dump LibStub("AceAddon-3.0"):GetAddon("Talented",true)`
> 
> If any of those return nil/error I'll have a better idea where the problem is.

No nil values anywhere.

**Comment by mikeacjones** [comment]
Does it load for you if you disable talented? I would think you would need to make this change first for that:

```
local _,_,_,talented_loadable, talented_error = GetAddOnInfo("Talented")
if talented_loadable and not (talented_error == "MISSING" or talented_error == "DISABLED") then
    if GetAddOnEnableState((GetUnitName("player")),"Talented") == 2 then
        local Talented = LibStub("AceAddon-3.0"):GetAddon("Talented",true)
        if Talented then
            hooksecurefunc(Talented, "ToggleTalentFrame", function()
                if (initRun) then return end
                UsingTalented = true
                init("TalentedFrame")
            end)
        end
    end
else
    hooksecurefunc("ToggleTalentFrame", function(...)
        if (PlayerTalentFrame == nil) then return end
        if (initRun) then return end
        init("PlayerTalentFrame")
    end)
end
```

**Comment by Road-block** [comment]
Does the third one also dump some kind of object? LibStub is a library included with Talented so it should be present when Talented is installed but doesn't hurt to make sure.

**Edit:** I will check my fork with Talented disabled.

**Comment by mikeacjones** [comment]
> Does the third one also dump some kind of object? LibStub is a library included with Talented so it should be present when Talented is installed but doesn't hurt to make sure.
> 
> **Edit:** I will check my fork with Talented disabled.

Yes the last one does return a rather large dump.

**Comment by Road-block** [comment]
Oh 💩 yes that's an obvious mistake, my else condition is at the wrong scope.

**Comment by mikeacjones** [comment]
> Oh 💩 yes that's an obvious mistake, my else condition is at the wrong scope.

image

Adding this in prints a `nil` in both locations. I don't think the Talented addon has been loaded at this stage. Could manually load it?

**Comment by Road-block** [comment]
Right, so it's a race condition from the other side. 
Alright ignore the pull request for now, I'll add some commits 😄

**Comment by mikeacjones** [comment]
> Right, so it's a race condition from the other side. Alright ignore the pull request for now, I'll add some commits 😄

When I throw debugging messages into Talented itself, the Frame doesn't get created until its toggled for the first time. The addon itself does load right away though.

**Comment by Road-block** [comment]
Right but I'm post-hooking [Talented/core.lua:347](https://github.com/Lethay/TalentedClassic/blob/master/Talented/core.lua#L347) which is the method in Talented that creates its main frame (through self:Update())

**Comment by mikeacjones** [comment]
Yup. Here is confirmation we're on the other side of the race condition:
Screen Shot 2022-01-21 at 2 08 47 AM
Screen Shot 2022-01-21 at 2 08 02 AM

**Comment by mikeacjones** [comment]
```
local _,_,_,talented_loadable, talented_error = GetAddOnInfo("Talented")
if talented_loadable and not (talented_error == "MISSING" or talented_error == "DISABLED") then
    if GetAddOnEnableState((GetUnitName("player")),"Talented") == 2 then
        local talentedLoaded = IsAddOnLoaded("Talented")
        if (not talentedLoaded) then LoadAddOn("Talented") end
        local Talented = LibStub("AceAddon-3.0"):GetAddon("Talented",true)
        Talented = LibStub("AceAddon-3.0"):GetAddon("Talented",true)
        if Talented then
            hooksecurefunc(Talented, "ToggleTalentFrame", function()
                if (initRun) then return end
                UsingTalented = true
                init("TalentedFrame")
            end)
        end
    end
else
    hooksecurefunc("ToggleTalentFrame", function(...)
        if (PlayerTalentFrame == nil) then return end
        if (initRun) then return end
        init("PlayerTalentFrame")
    end)
end
```

This works

**Comment by Road-block** [comment]
I was thinking along similar lines without force loading Talented.
```lua
local _,_,_,talented_loadable, talented_error = GetAddOnInfo("Talented")
if talented_loadable and not (talented_error == "MISSING" or talented_error == "DISABLED") then
    local Talented
    if GetAddOnEnableState((GetUnitName("player")),"Talented") == 2 then
        local loaded, finished = IsAddOnLoaded("Talented")
        if loaded and finished then
            Talented = LibStub("AceAddon-3.0"):GetAddon("Talented",true)
        else
            local talented_loader = CreateFrame("Frame")
            talented_loader:SetScript("OnEvent", function(self,event,...)
                if (...) == "Talented" then
                    self:UnregisterEvent("ADDON_LOADED")
                    Talented = LibStub("AceAddon-3.0"):GetAddon("Talented",true)
                end
            end)
            talented_loader:RegisterEvent("ADDON_LOADED")
        end
        if Talented then
            hooksecurefunc(Talented, "ToggleTalentFrame", function()
                if (initRun) then return end
                UsingTalented = true
                init("TalentedFrame")
            end)
        else
            hooksecurefunc("ToggleTalentFrame", function(...)
                if (PlayerTalentFrame == nil) then return end
                if (initRun) then return end
                init("PlayerTalentFrame")
            end)
        end
    end
else
    hooksecurefunc("ToggleTalentFrame", function(...)
        if (PlayerTalentFrame == nil) then return end
        if (initRun) then return end
        init("PlayerTalentFrame")
    end)
end
```

This works for me with our without Talented enabled.
Just to satisfy my curiosity can you test if it works locally on your machine?

**Comment by mikeacjones** [comment]
> I was thinking along similar lines without force loading Talented.
> 
> ```lua
> local _,_,_,talented_loadable, talented_error = GetAddOnInfo("Talented")
> if talented_loadable and not (talented_error == "MISSING" or talented_error == "DISABLED") then
>     local Talented
>     if GetAddOnEnableState((GetUnitName("player")),"Talented") == 2 then
>         local loaded, finished = IsAddOnLoaded("Talented")
>         if loaded and finished then
>             Talented = LibStub("AceAddon-3.0"):GetAddon("Talented",true)
>         else
>             local talented_loader = CreateFrame("Frame")
>             talented_loader:SetScript("OnEvent", function(self,event,...)
>                 if (...) == "Talented" then
>                     self:UnregisterEvent("ADDON_LOADED")
>                     Talented = LibStub("AceAddon-3.0"):GetAddon("Talented",true)
>                 end
>             end)
>             talented_loader:RegisterEvent("ADDON_LOADED")
>         end
>         if Talented then
>             hooksecurefunc(Talented, "ToggleTalentFrame", function()
>                 if (initRun) then return end
>                 UsingTalented = true
>                 init("TalentedFrame")
>             end)
>         else
>             hooksecurefunc("ToggleTalentFrame", function(...)
>                 if (PlayerTalentFrame == nil) then return end
>                 if (initRun) then return end
>                 init("PlayerTalentFrame")
>             end)
>         end
>     end
> else
>     hooksecurefunc("ToggleTalentFrame", function(...)
>         if (PlayerTalentFrame == nil) then return end
>         if (initRun) then return end
>         init("PlayerTalentFrame")
>     end)
> end
> ```
> 
> This works for me with or without Talented enabled. Just to satisfy my curiosity can you test if it works locally on your machine?

Added this in and it isn't working - the talent sequence is no longer loading.

**Comment by Road-block** [comment]
I deleted it because it's way past my sleep time (EU) and I'm not thinking straight, the snippet is obviously broken on a closer look, it has a logic error.

**Comment by mikeacjones** [comment]
```
local _,_,_,talented_loadable, talented_error = GetAddOnInfo("Talented")
if talented_loadable and not (talented_error == "MISSING" or talented_error == "DISABLED") then
    local Talented
    if GetAddOnEnableState((GetUnitName("player")),"Talented") == 2 then
        local loaded, finished = IsAddOnLoaded("Talented")
        if loaded and finished then
            Talented = LibStub("AceAddon-3.0"):GetAddon("Talented",true)
            hookTaleneted(Talented)
        else
            print("creating talented_loader")
            local talented_loader = CreateFrame("Frame")
            talented_loader:SetScript("OnEvent", function(self,event,...)
                print("event fired")
                print(...)
                if (...) == "Talented" then
                    print("we found talented")
                    self:UnregisterEvent("ADDON_LOADED")
                    Talented = LibStub("AceAddon-3.0"):GetAddon("Talented",true)
                    hookTaleneted(Talented)
                end
            end)
            talented_loader:RegisterEvent("ADDON_LOADED")
        end
    end
else
    hooksecurefunc("ToggleTalentFrame", function(...)
        if (PlayerTalentFrame == nil) then return end
        if (initRun) then return end
        init("PlayerTalentFrame")
    end)
end
```

This works. You were trying to use `Talented` which was being set by an event, before it gets set, in my race case. Played around with it and can see the event hooking you were doing via the `Frame` was sound.

**Comment by Road-block** [comment]
Just to dump my last edit (not looking to re-open)
```lua
local function hookBlizzard()
    hooksecurefunc("ToggleTalentFrame", function(...)
        if (PlayerTalentFrame == nil) then return end
        if (initRun) then return end
        init("PlayerTalentFrame")
    end)
end

local function hookTalented(Talented)
    hooksecurefunc(Talented, "ToggleTalentFrame", function()
        if (initRun) then return end
        UsingTalented = true
        init("TalentedFrame")
    end)
end

function ts.SetTalentEditor()
    local _,_,_,talented_loadable, talented_error = GetAddOnInfo("Talented")
    if talented_loadable and not (talented_error == "MISSING" or talented_error == "DISABLED") then
        if GetAddOnEnableState((GetUnitName("player")),"Talented") == 2 then
            local loading, finished = IsAddOnLoaded("Talented")
            if loading and finished then
                local Talented = LibStub("AceAddon-3.0"):GetAddon("Talented",true)
                hookTalented(Talented)
                return
            else
                local talented_loader = CreateFrame("Frame")
                talented_loader:SetScript("OnEvent", function(self,event,...)
                    if (...) == "Talented" then
                        return ts.SetTalentEditor()
                    end
                end)
                talented_loader:RegisterEvent("ADDON_LOADED")
                return
            end
        else
            hookBlizzard()
        end
    else
        hookBlizzard()
    end
end
ts.SetTalentEditor()
```
I know it's closed and may it rest in peace 🥀

**Comment by mikeacjones** [comment]
Haha. Since this seems more to me a code cleanup - and a worthwhile one, don't mistake me - I'll roll it into the next update I do. I plan to hold the update until I have something to add for players. The way you hooked Talented has me thinking about hooking their import function, checking if its the same class you're currently on, and then importing it or offering to import it into Talent Sequence.

**Comment by mikeacjones** [comment]
@Road-block Seriously, thank you for jumping in on this. You helped a ton with this. I will say this has put the bug to go and actually learn LUA in me haha. Went from just a quick and dirty patch that I thought other people might get use out of, to wanting to go learn the syntax and functionality of a language/API.

**Comment by Road-block** [comment]
This is still fairly relevant: https://www.wowinterface.com/forums/showthread.php?t=47695
This is a good starting place for novices with programming in general more so than addon crafting (you are way past that point, but might still find a useful piece of info here and there) https://wowpedia.fandom.com/wiki/HOWTOs

https://www.lua.org/manual/5.1/ is the reference for the Lua version embedded in the wow client.
You'd ignore all the os.* and io.* parts they don't apply to wow (or rather are outside the scope of what addon authors can interact with).

This despite being a fossil is still very relevant for some gotchas https://www.lua.org/gems/sample.pdf
Similarly a quick cheat sheet http://thomaslauer.com/download/luarefv51single.pdf

Finally some more wow-specific resources that are useful would be
https://www.townlong-yak.com/globe/ is a static code analysis tool that can help you catch some of the more obvious bad smells (unintended globals writes, unintended global accesses - typos etc)
You can also setup tooling for it locally but this is convenient.

Browsing Blizzard's own interface files by extracting them from the client yourself: https://wowpedia.fandom.com/wiki/Viewing_Blizzard%27s_interface_code or downloading them from an online repo like https://github.com/Gethe/wow-ui-source/tree/classic

https://github.com/Stanzilla/WoWUIBugs/wiki and https://github.com/Stanzilla/WoWUIBugs/issues?page=1&q=is%3Aopen+is%3Aissue+label%3ABCC as more of an undocumented/recent findings resource.

**Comment by mikeacjones** [comment]
Very nice :) Next I'm just going to focus on adding in some GitHub Actions to make this easier on me haha.

**Comment by mikeacjones** [comment]
@Road-block you know, I think adding WowHead was a really good idea because it _should_ work with classic too. I can't really find a user usable talent calculator for icy veins for classic, but the WowHead one should be backwards compatible. I'll have to give it a try later.

**Pull request closed without merging**
